tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = "go build -o ./tmp/main ."
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "scripts"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  post_cmd = []
  pre_cmd = []
  watch_dir = [".", "internal", "pkg", "web"]
  main = "main.go"
  poll = true

[log]
  main_only = false
  silent = false
  time = false
  level = "debug"

[hotreload]
  enabled = true
  delay = 1000
  notify = true
  cmd = "killall -SIGUSR2 {{binary}}"